var res = {
    HelloWorld_png: "res/HelloWorld.png",
    CloseNormal_png: "res/CloseNormal.png",
    CloseSelected_png: "res/CloseSelected.png",
    boton_jugar_png: "res/boton_jugar.png",
    boton_saltar_png: "res/IULayer/boton_saltar.png",
    boton_menu_png: "res/IULayer/boton_menu.png",
    fondomenu_png: "res/Fondos/Fondo_Inicio.png",
    fondomenu3_png: "res/Fondos/Fondo_menu.png",
    fondomenu4_png: "res/Fondos/Fondo_menu2.png",
    arco_png: "res/Armas/arco.png",
    boomeran_png: "res/Armas/boomeran.png",
    espada_png: "res/Armas/espada.png",
    bomba_png: "res/Armas/bomba.png",
    arco_reducido_png: "res/Armas/arco_reducido.png",
    boomeran_reducido_png: "res/Armas/boomeran_reducido.png",
    espada_reducida_png: "res/Armas/espada_reducida.png",
    bomba_reducida_png: "res/Armas/bomba_reducida.png",
    rupia_png: "res/Colectables/rupia.png",
    rupia_amarilla_png: "res/Colectables/rupia_amarilla.png",
    rupia_roja_png: "res/Colectables/rupia_roja.png",
    rupiaazul_png: "res/IULayer/rupiaazul.png",
    rupiaazul_colectable_png: "res/Colectables/rupiaazul_colectable.png",
    corazon_png: "res/IULayer/corazon.png",
    corazon_salvaje_png: "res/Colectables/corazon_salvaje.png",
    corazonnegro_png: "res/IULayer/corazonnegro.png",
    contenedorCorazon_png: "res/IULayer/contenedorcorazon.png",
    corazonblanco_png : "res/IULayer/corazonblanco.png",
    Outside_A5_png: "res/Mapas/MapaA/Outside_A5.png",
    octorok_png: "res/Animaciones/octorok.png",
    octorok_plist: "res/Animaciones/octorok.plist",
    tileb_png: "res/Mapas/MapaA/tileb.png",
    mapa_inicial_tmx: "res/Mapas/MapaA/mapa_inicial.tmx",
    boomerang_png:"res/Animaciones/boomerang.png",
    boomerang_plist:"res/Animaciones/boomerang.plist",
    Ravenna_ttf:"res/ravenna.ttf",
    explosion_plist:"res/Animaciones/explosion.plist",
    bomb_png:"res/Animaciones/bomba.png",
    link_png:"res/Animaciones/link.png",
    link_plist:"res/Animaciones/link.plist",
    jarron_plist:"res/Interaccionables/Jarron.plist",
    jarron_png:"res/Interaccionables/Jarron.png",

};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}